# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e95a86438b2ad9e2a9953ef45bbb7d4c47f93ab1a2170aa16b1cf60430e8d5594413df5dc21fe45b5135761dd6c659432f7c10db1ea74ebbff2f80dff1a56b15

test:
  secret_key_base: c8c239036ae49f9eb677a321b1596e13f0353356198ec1df6987c6b1dd4562deda553bea547db0c315f9c577cf21c0e88c45e00615be935a9c798e7befa02db7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
